#!/bin/bash

magenta='\033[1;95m'
white='\033[1;97m'
yellow='\033[0;93m'
NC='\033[0m'
clear
if [ -f "/etc/openvpn/server/openvpn-tcp.log" ]; then
    echo ""
    echo -e "${magenta}──────────[${NC} ${white}OpenVPN TCP User Login${NC} ${magenta}]──────────${NC}"
    echo -e "${yellow}Username${NC} ${magenta} |${NC} ${yellow}      IP Address${NC} ${magenta}      |${NC}${yellow} ${yellow}Connected${NC}"
    echo -e "${magenta}──────────────────────────────────────────────${NC}"
    cat /etc/openvpn/server/openvpn-tcp.log | grep -w "^CLIENT_LIST" | cut -d ',' -f 2,3,8 | sed -e 's/,/      /g' > /tmp/vpn-login-tcp.txt
    cat /tmp/vpn-login-tcp.txt
fi

echo -e "${magenta}──────────────────────────────────────────────${NC}"

if [ -f "/etc/openvpn/server/openvpn-udp.log" ]; then
    echo " "
    echo -e "${magenta}──────────[${NC}${white} OpenVPN UDP User Login${NC} ${magenta}]──────────${NC}"
    echo -e "${yellow}Username${NC} ${magenta} |${NC} ${yellow}      IP Address${NC} ${magenta}      |${NC}${yellow} ${yellow}Connected${NC}"
    echo -e "${magenta}──────────────────────────────────────────────${NC}"
    cat /etc/openvpn/server/openvpn-udp.log | grep -w "^CLIENT_LIST" | cut -d ',' -f 2,3,8 | sed -e 's/,/      /g' > /tmp/vpn-login-udp.txt
    cat /tmp/vpn-login-udp.txt
fi

echo -e "${magenta}──────────────────────────────────────────────${NC}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu